services:
  data:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file: .env
    
  server:
    build: .
    container_name: pharmacy
    restart: unless-stopped
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - data